### ISSUE TITLE
Fix segfault on OSX

### ISSUE THREAD

**Issue by colebrumley** [colebrumley/tlspxy#17]
I'm getting a segfault on OSX when loading the system roots on Go 1.9:

```
DEBU[0000] Loading default remote TLS config [verify: true, system roots: true] 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1168e9b]

goroutine 1 [running]:
crypto/x509.(*CertPool).AddCert(0x0, 0xc42029c000)
	/usr/local/Cellar/go/1.9/libexec/src/crypto/x509/cert_pool.go:95 +0x6b
crypto/x509.(*CertPool).AppendCertsFromPEM(0x0, 0xc420200000, 0x41f85, 0x7fe00, 0x0)
	/usr/local/Cellar/go/1.9/libexec/src/crypto/x509/cert_pool.go:128 +0x13a
main.loadSysroots(0x0, 0xc420057be8, 0x2, 0x2)
	/Users/cole.brumley/lib/go/src/github.com/colebrumley/tlspxy/roots_darwin.go:16 +0xaa
main.SetSystemCAPool(0x0, 0x40, 0xc420057be8, 0x2)
	/Users/cole.brumley/lib/go/src/github.com/colebrumley/tlspxy/ca.go:8 +0x2b
main.configRemoteTLS(0xc420048c30, 0xc42000e160, 0xc420048c30, 0x151dc40)
	/Users/cole.brumley/lib/go/src/github.com/colebrumley/tlspxy/remotetls.go:44 +0x38a
main.main()
	/Users/cole.brumley/lib/go/src/github.com/colebrumley/tlspxy/main.go:83 +0x434
```

**Comment by colebrumley** [comment]
Fixed in 24b810f. Replaced all platform-specific `loadSysroots` implementations with a direct call to `x509.SystemCertPool()` (supported on all platforms since Go 1.18). Also fixed a logic bug in `remotetls.go` where the first `SetSystemCAPool` result was silently discarded, and removed the now-unnecessary `roots_darwin.go`, `roots_linux.go`, and `roots_windows.go` files.
